title: sunaba
email: sunabagame@gmail.com
description: >-
  The 3D sandbox game
domain: sunaba.gg 
baseurl: "/"
url: "https://sunaba.gg"
twitter_username: SunabaGame
github_username:  sunabagg

google_analytics: G-M6FEVBYZXR
theme: minima
plugins:
  - jekyll-feed

sass:
  load_paths:
    - _sass

defaults:
  - scope:
      path : "assets/images"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

