title: sunaba
email: sunabagame@gmail.com
description: >-
  The open source 3D sandbox game
domain: m1ntkat.github.io 
baseurl: "/sunaba-site"
url: "https://m1ntkat.github.io"
twitter_username: mintkatDev
github_username:  m1ntkat

theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

